const MenuApi =[{
    id: 1,
    image: "images/maggi.jpeg",
    name: "maggi",
    category: "breakfast",
    price: "12₹",
    description: "Maggi noodles are dried noodles fused with oil, and sold with a packet of flavorings. These noodles are usually eaten after being cooked in boiling water for 3 to 5 minutes or eaten straight from the packet. Just boil the water, add the tastemaker and noodles and your maggi is ready within 2 to 3 minutes.",
},
{
    id: 2,
    image: "images/allu_pakoda.jpeg",
    name: "allu pakoda",
    category: "evening",
    price: "20₹",
    description: "Ensure the oil is hot enough, otherwise, pakodas will soak up more oil leading to more fat. But if it is too hot, pakodas will turn dark brown from the outside, but may not properly cook from the inside. To check the temperature, slide a tiny piece of the batter first. It should rise and not turn brown too quickly.",
},
{
   id: 3,
   image: "images/chola.jpeg",
   name: "chola bhatura",
   category: "breakfast",
   price: "35₹",
   description: "Chole bhature (Hindi: छोले भटूरे) is a food dish popular in the Northern areas of the Indian subcontinent. It is a combination of chana masala (spicy white chickpeas) and bhatura/puri, a deep-fried bread made from maida. Chole bhature is often eaten as a breakfast dish, sometimes accompanied with lassi.",
},
{
    id: 4,
    image: "images/corn.jpeg",
    name: "corn",
    category: "evening",
    price: "20₹",
    description: "Cornmeal is a meal (coarse flour) ground from dried corn. It is a common staple food, and is ground to coarse, medium, and fine consistencies, but not as fine as wheat flour can be. In Mexico, very finely ground cornmeal is referred to as corn flour.",
},
{
    id: 5,
    image: "images/non_veg_thali.jpeg",
    name: "non veg",
    category: "lunch",
    price: "100₹",
    description: "'Non-vegetarian' food is a term commonly used in India for food that has meat, fish, or eggs in it. It is more commonly called non-veg food. Not just for food, it can be used for a person too - a person eating meat is a non-vegetarian in Indian English. Egg too is not classified as vegetarian for Indians. Well, they are called 'eggitarians'.",
},
{
   id: 6,
   image: "images/pau_bhaji.jpeg",
   name: "pau bhaji",
   category: "breakfast",
   price: "35₹",
   description: "Pav Bhaji is a fast food dish from Mumbai (Bombay), India, consisting of a vegetable curry (bhaji) cooked in tomato gravy and served with a soft bread roll (pav).",
},
{
    id: 7,
    image: "images/pizza.jpeg",
    name: "pizza",
    category: "evening",
    price: "50₹",
    description: "pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot ...",
},
{
    id: 8,
    image: "images/puri.jpeg",
    name: "puri",
    category: "breakfast",
    price: "35₹",
    description: "Puri (sometimes spelled as poori) is a deep-fried bread made from unleavened whole-wheat flour that originated in the Indian subcontinent. It is eaten for breakfast or as a snack or light meal. It is usually served with a savory curry or bhaji, as in puri bhaji, but may also be eaten with sweet dishes.", 
},
{
    id: 9,
    image: "images/rajmarice.jpeg",
    name: "rajmarice",
    category: "dinner",
    price: "85₹",
    description: "Rajma chawal or rajma rice is delicious rajma masala (red kidney beans masala) mixed with rice, a comfort food for many who grew up eating this great combination of carbs and protein. While I personally got introduced to the joys of rajma chawal fairly recently, I don’t deny how comforting.",
},
{
    id: 10,
    image: "images/roti_with_meat.jpeg",
    name: "roti with meat",
    category: "dinner",
    price: "85₹",
    description: "Roast beef, French style. Beef roasted in the French style is served quite rare, and for a small roast a French butcher may instruct you to cook it for as little as 10 minutes. Unless the roast is quite long and narrow, e.g. a thin fillet, you will need to roast it longer than that.",
},
{
    id: 11,
    image: "images/samosa.jpeg",
    name: "samossa",
    category: "evening",
    price: "25₹",
    description: "A samosa (/səˈmoʊsə/) or singara is a fried South Asian pastry with a savoury filling, including ingredients such as spiced potatoes, onions, and peas. It may take different forms, including triangular, cone, or half-moon shapes, depending on the region.",
},
{
    id: 12,
    image: "images/sweet.jpeg",
    name: "sweet",
    category: "breakfast",
    price: "20₹",
    description: "Dulcet is sweet, honeyed, pleasant, in a gentle way, something in harmony with your taste or likings. It is never harsh. Dulcified is what has been made sweeter, or softer, in taste, edulcorated, sweetened.",
},
{
    id: 13,
    image: "images/vegthali.jpeg",
    name: "veg thali",
    category: "lunch",
    price: "70₹",
    description: "These katoris are placed along the edge of the round tray, the actual thali; sometimes a steel tray with multiple compartments is used. Typical dishes include rice, dal, vegetables, roti, papad, dahi (yogurt), small amounts of chutney or pickle, and a sweet dish.",
},
]

export default MenuApi;
